### ISSUE TITLE
Consult:  Mitre ATT&CK Adversary Datasets

### ISSUE THREAD

**Issue by dfirence** [cmu-sei/CDAS#2]
Hi

Does your project work with the **Mitre ATT&CK** Adversaries?

Like if I wanted to have an emulation/simulation model from CDAS on `apt-c-36`, how would I use your project?

**Comment by sei-awhisnant** [comment]
@dfirence CDAS does work Mitre ATT&CK. The default set of actors is from ATT&CK, and we're currently working to include more from that set. The latest updates to CDAS also allow for much greater customization of inputs, so you can provide whatever APTs you want if you don't want the default set. The screenshot below shows a run of CDAS configured to use the default set of APTs with generated countries and json output. 

![Screen Shot 2021-01-22 at 9 25 19 AM](https://user-images.githubusercontent.com/69045289/105502740-c16c9a00-5c93-11eb-8ced-f2107bce2452.png)
